name: Changelogs - Daily Compile

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  compile:
    name: Compile Daily Changelogs
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 25
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'
          cache: 'pip'
          cache-dependency-path: '**/changelogs/requirements.txt'
      - name: Fetch dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r **/changelogs/requirements.txt
      - name: Compile Daily Changelogs into Monthly file
        run: python tools/changelogs/compile_monthly_changelogs.py -vv
      - name: Disable Branch Protection
        uses: benjefferies/branch-protection-bot@6d0ac2b2d9bfd39794b017f8241adb7da7f0ab98
        if: always()
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.repository.default_branch }}
      - name: Commit and Push Compiled Changelog
        run: |
          git config user.name hrzn-actions
          git config user.email 68955348+hrzn-actions@users.noreply.github.com
          git add html/changelogs
          git diff-index --quiet --cached HEAD || git commit -m "Automatic daily changelog compile [ci skip]"
          git push
      - name: Re-enable Branch Protection
        uses: benjefferies/branch-protection-bot@6d0ac2b2d9bfd39794b017f8241adb7da7f0ab98
        if: always()
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.repository.default_branch }}
